Release/0.5.0
nextimecode/f02-web-academia pull request #12
Opened 2021-03-12 21:51 UTC by priscilladeroode

- Adicionados os cards de planos;

2021-03-12 22:27 UTC, phdduarte requested changes

2021-03-12 22:27 UTC, phdduarte commented on src/styles/custom/style.scss
> +    background-color: $black !important;
Acredito que nao precisa desses !important 
se caso funcionar pode retirar 
porque as boas praticas é nao usar.

2021-03-12 22:27 UTC, phdduarte commented on src/styles/custom/style.scss
> +    // text-shadow: 0px 0px 20px rgb(0 0 0 / 70%);
pode remover esse comentario

2021-03-12 22:27 UTC, phdduarte commented on src/styles/global.scss
> +@import '../../node_modules/bootstrap/scss/bootstrap.scss';
porque essa alteração foi feita ?

2021-03-13 14:54 UTC, priscilladeroode commented on src/styles/custom/style.scss
> +    background-color: $black !important;
Se não colocar o !important a cor não está sendo aplicada.

2021-03-13 14:54 UTC, priscilladeroode commented on src/styles/custom/style.scss
> +    // text-shadow: 0px 0px 20px rgb(0 0 0 / 70%);
Ok! removido.

2021-03-13 14:55 UTC, priscilladeroode commented on src/styles/global.scss
> +@import '../../node_modules/bootstrap/scss/bootstrap.scss';
Desfiz a alteração.

2021-03-13 18:17 UTC, phdduarte approved these changes

2021-03-13 18:17 UTC, merged