Release/0.11.0
nextimecode/f02-web-academia pull request #25
Opened 2021-03-20 02:24 UTC by marcuslamounier

2021-03-20 04:02 UTC, priscilladeroode requested changes

2021-03-20 04:02 UTC, priscilladeroode commented on src/components/organisms/bemVindo/index.tsx
> +                            transformarama vida dos alunos. São mais de 6 mil na
Esse texto está com erro de português, não acha melhor corrigir de uma vez?

2021-03-20 04:04 UTC, priscilladeroode requested changes

2021-03-20 04:04 UTC, priscilladeroode commented on src/components/organisms/planos/index.tsx
> +                price: 40,
Esse card da consultoria personalizada ao invés de preço possui apenas um texto.

2021-03-21 01:13 UTC, priscilladeroode approved these changes

2021-03-22 12:43 UTC, priscilladeroode approved these changes

2021-03-22 12:49 UTC, phdduarte requested changes

2021-03-22 12:49 UTC, phdduarte commented on src/components/atoms/price/index.tsx
> +        <div className="my-4 d-flex text-warning d-flex justify-content-center">
O atom deve ficar apenas com o elemento 
para que voce nao interfira onde ele deva ficar quando chamado em outro lugar.

Quem deve falar a posição do atoms é o template 
<div className="my-4 d-flex text-warning d-flex justify-content-center">
essas divs que mudam a posição deve ir para a parte de cima do codigo 
ou seja para o template.

2021-03-22 12:49 UTC, phdduarte commented on src/components/organisms/bemVindo/index.tsx
> +                            Vinícius Dias é ex-atleta e ex-jogador de futebol.
Esse texto deve ficar na pagina, 
organisms e tempalte deve receber props 

as paginas que devem possuir os textos e passar para dentro dos organismos.

2021-03-22 14:04 UTC, marcuslamounier commented on src/components/organisms/planos/index.tsx
> +        <section id="planos" style={{ paddingTop: '80px' }}>
criada nova classe

2021-03-22 14:04 UTC, marcuslamounier commented on src/components/atoms/price/index.tsx
> +        <div className="my-4 d-flex text-warning d-flex justify-content-center">
item movido a molécula e o desmembramento gerou 3 átomos

2021-03-22 14:05 UTC, marcuslamounier commented on src/components/organisms/bemVindo/index.tsx
> +                            Vinícius Dias é ex-atleta e ex-jogador de futebol.
incluído na página inicial e passado como propriedade

2021-03-22 14:05 UTC, marcuslamounier reviewed
sugestões corrigidas

2021-03-23 11:09 UTC, phdduarte approved these changes

2021-03-23 11:52 UTC, merged